name: QSFindItemAddOn
version: ${project.version}
main: io.mysticbeans.finditemaddon.FindItemAddOn
api-version: 1.16
authors: [ ronsane ]
softdepend:
  - QuickShop
  - QuickShop-Hikari
  - PlayerWarps
  - WorldGuard
  - Essentials

permissions:
  finditem.use:
    description: Enables players to use the /finditem command
    default: true
  finditem.hideshop:
    description: Enables players to use the /finditem hideshop & /finditem revealshop
    default: true
  finditem.reload:
    description: For OP. Enables use of '/finditem reload' to reload the config
    default: op
  finditem.restart:
    description: For OP. Enables use of '/finditem restart' to restart the plugin
    default: op
  finditem.admin:
    description: For OP. Enables use of all admin commands
    default: op
  finditem.shoptp:
    description: If 'allow-direct-shop-tp' is enabled in config, players require this permission to be able to teleport
    default: op