name: QSFindItemAddOn
version: ${project.version}
main: io.myzticbean.finditemaddon.FindItemAddOn
api-version: 1.16
authors: [ myzticbean ]
softdepend:
  - QuickShop
  - QuickShop-Hikari
  - PlayerWarps
  - WorldGuard
  - Essentials
  - Residence

permissions:
  finditem.use:
    description: Enables players to use the /finditem command
    default: true
  finditem.hideshop:
    description: Enables players to use the /finditem hideshop & /finditem revealshop
    default: true
  finditem.reload:
    description: For OP. Enables use of '/finditemadmin reload' to reload the config
    default: op
  finditem.admin:
    description: For OP. Enables use of all admin commands
    default: op
  finditem.shoptp:
    description: If 'allow-direct-shop-tp' is enabled in config, players require this permission to be able to teleport
    default: op
  finditem.shoptp.own:
    description: Allows teleporting to own shops
    default: true
  finditem.shoptp-delay.bypass:
    description: Bypass the TP delay for teleporting to shop
    default: op